version: 0.0
os: linux 
hooks:
  ApplicationStop:
    - location: /node/bin/stop.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: /node/bin/install_dependencies.sh
      timeout: 600
      runas: root
    - location: /node/bin/start.sh
      timeout: 600
      runas: root
    - location: /node/bin/test.sh
      timeout: 600
      runas: root